---
framework: mocha
modifiers:
  - type: mocha
    config: cnf/mocha.ini
postmerge:
  pattern:
    - "./test/**/*.spec.ts"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
premerge:
  - "./test/**/*.spec.ts"
stability:
  consecutive_runs: 5
prerun:
  - npm ci
postrun:
  - node --version
version: 2.0
